### ISSUE TITLE
Getting error  Cannot call method 'reject' of null

### ISSUE THREAD

**Issue by Singha2** [tracker1/mssql-ng#2]
```
return Promise.reject(err);
               ^
```

TypeError: Cannot call method 'reject' of null
    at getConnection (E:\Amit Singh Personal\Testing\node_modules\mssql-ng\dist\
connections\open.js:43:20)
    at null.<anonymous> (E:\Amit Singh Personal\Testing\loadCSVData.js:28:12)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (_stream_readable.js:745:14)
    at EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:407:10)
    at emitReadable (_stream_readable.js:403:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Readable.push (_stream_readable.js:127:10)
    at Transform.push (_stream_transform.js:140:32)
    at Parser._emit (E:\Amit Singh Personal\Testing\node_modules\csv-parser\inde
x.js:164:8)
    at Parser._online (E:\Amit Singh Personal\Testing\node_modules\csv-parser\in
dex.js:136:10)
    at Parser._transform (E:\Amit Singh Personal\Testing\node_modules\csv-parser
\index.js:71:14)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)

My code is as below,

var csv = require('csv-parser');
var fs = require('fs');
var mssql  = require('mssql-ng');

var args = process.argv.slice(2);

var fileName = args[0].toString();

var config = {
    user: '',
    password: '',
    server: '', 
    database: ''
}
// Credetials are correct.
var stream = csv({
  raw: false,    // do not decode to utf-8 strings
  separator: '~', // specify optional cell separator
  newline: '\n' // specify a newline character
});

fs.createReadStream(fileName)
  .pipe(stream)
  .on('data', function(data) {
    //console.log(data.TransactionID);
    //processOrderhdr(data.TransactionID);

```
var sql = mssql(config);
var value = data.TransactionID; 
value = value.toString();
```

sql.then(function(conn){
          //use connection
          //var request = new mssql.Request(conn);

```
     var ps = new mssql.PreparedStatement(conn);



      ps.input('PolicyId', sql.VarChar);

      ps.prepare('INSERT INTO PIPFILESDB(COLUMN1) VALUES (@PolicyId)', function(err) {


ps.execute({'PolicyId':value}, function(err, recordset) {
//console.log(recordset);


    ps.unprepare(function(err) {

        //console.log(err);

    });
});
});




    });
```

  })

**Comment by tracker1** [comment]
@Singha2  What environment are you running in?  If you look at the requirements you need to be running a node environment with either native promises and/or include `bluebird`. `es6-promise` or `es6-promises` in your project.

This module really works best with babeljs, so that you can use it with the template processing... otherwise, you may want to simply use [mssql](https://www.npmjs.com/package/mssql) this library is a wrapper around mssql, and provides a few niceties if you're running in a newer JS environment either via babel, or the latest iojs with es6 features.

**Comment by Singha2** [comment]
I am using it on windows and node @ 0.10. I simply run npm install mssql-ng this installs msssql.
I am using mssql-ng@1.5.1 . Installing mssql-ng installs other dependencies. I can see it used "i-promise" and that is installed.
Original mssql module is creating problem as I am running approx 20K running insert script as a consumer of raabitmq.

This module seem to be excellent but this is not working for me. I am getting above mentioned error.

I am not sure how to use other promise modules.

**Comment by tracker1** [comment]
Just `npm install bluebird` but I'd recommend an `npm install mssql` and use that instead, if you aren't using promises or other es6 features...

**Comment by Singha2** [comment]
Thanks, it worked after installation of bluebird and minor code change in mssql-ng/src/connections/open.js --> var Promise = require('bluebird');
I am thinking to use it because I am facing problem with "mssql" module when no of connections increases. 

Do you see any problem with this module ?

**Comment by tracker1** [comment]
I've used it a bunch, one thing it does that the parent doesn't is ensure the same pool is used when the same connection string is used... I'd suggest moving to 0.12 or current iojs of you can, and with Babel or optional features you can do much more.

**Comment by Singha2** [comment]
Thanks, because of this feature large no of transactions works with this module as it uses same connection pool. Or I might be doing something wrong with parent "mssql" module. As this modules uses same pool again and again, I think connection closing is not that important. While parent module close connection must be handled gracefully else pool will get drained and it shows "can not get acquire of null".

If you have any good example please share it with parent module.
